import { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Footer } from '@/components/footer/footer.component';
import { Header } from '@/components/header/header.component';
import '../styles/globals.css';

const inter = Inter({ subsets: ['latin'] });
export const metadata: Metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
